version: '3.8'
services:
  postgres:
    container_name: pg_database_zentify
    image: postgres
    ports:
      - 5432:${PG_DATABASE_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
