@baseUrl = http://localhost:8000/api/v1/user/auth


# @name register_by_email

POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "pedro",
    "email": "pedluiz321@gmail.com",
    "password": "123456"
}

###

# @name login_with_email

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "pedluiz321@gmail.com",
    "password": "password"
}

###

# @name email_verify

GET {{baseUrl}}/verify/kdjaklfjalkfjklajfjakljfkjaklgs.png


###

# @name forget_password

POST {{baseUrl}}/forget-password
Content-Type: application/json

{
    "email": "pedluiz321@gmail.com"
}


###

# @name reset_password

POST {{baseUrl}}/reset-password
Content-Type: application/json

{
    "password": "password",
    "code": "02f51e71e1"
}

